## Preliminaries

```python
1. torch.arange: generate increasing sequence, return "tensor"

2. tensor.shape: shape
3. tensor.numel:
3. tensor.reshape(others,row,col)
```

In [16]:
import torch
x=torch.arange(12)
print(x)
print(x.shape)
print(x.numel())
X=x.reshape(3,4)
print(X)
print(X.shape)
print(X.numel)
print(torch.zeros((2,3,4)))
print(torch.ones(2,2))
print(torch.rand(2,2))
print(torch.randn(2,2))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
<built-in method numel of Tensor object at 0x7f6ffe0a7e00>
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.7624, 0.7603],
        [0.7381, 0.9149]])
tensor([[ 0.5657, -0.8454],
        [ 1.0570, -1.2559]])


In [18]:
# 运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y, x*y


(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]),
 tensor([ 2.,  4.,  8., 16.]))

In [19]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [20]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [21]:
print(X.shape)
print(Y.shape)

torch.Size([3, 4])
torch.Size([3, 4])


In [28]:
# cat的意思可以理解为加和某一个轴的元素
print(torch.cat((X,Y),dim=0).shape)
print(torch.cat((X,Y),dim=1).shape)

torch.Size([6, 4])
torch.Size([3, 8])


## broadcasting


In [29]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [31]:
c=a+b
c

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [39]:
# 切片在这里也可用
c[0,-1],c[:,-1]

(tensor(1), tensor([1, 2, 3]))

In [48]:
# .item转换成python标量
c[0,0].item()

0

## 2.2 数据预处理
pandas

In [49]:
import os
os.mkdir("./data/")

In [50]:
with open("./data/house_tiny.csv","w") as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [51]:
import pandas as pd

In [52]:
data=pd.read_csv("./data/house_tiny.csv")
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [53]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [54]:

inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [55]:
# pandas转tensor
import torch
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

## 2.3 线性代数

In [56]:
# 标量
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [57]:
# 向量，标里的列表
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [ ]:
# 长度=维度，多维叫形状
len(x),x.shape()

## 2.4 微分

In [98]:
import numpy as np

def f(x):
    return 3 * x ** 2 - 4 * x

In [99]:
def numerical_lim(f, x, h):
    return (f(x + h) - f(x)) / h

h = 0.1
for i in range(5):
    print(f'h={h:.5f}, numerical limit={numerical_lim(f, 1, h):.5f}')
    h *= 0.1

h=0.10000, numerical limit=2.30000
h=0.01000, numerical limit=2.03000
h=0.00100, numerical limit=2.00300
h=0.00010, numerical limit=2.00030
h=0.00001, numerical limit=2.00003


In [102]:
from matplotlib import pyplot as plt
from IPython import display

def use_svg_display():  #@save
    """使用svg格式在Jupyter中显示绘图。"""
    display.set_matplotlib_formats('svg')
    
def set_figsize(figsize=(3.5, 2.5)):  #@save
    """设置matplotlib的图表大小。"""
    use_svg_display()
    d2l.plt.rcParams['figure.figsize'] = figsize
    
def set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend):
    """设置matplotlib的轴。"""
    axes.set_xlabel(xlabel)
    axes.set_ylabel(ylabel)
    axes.set_xscale(xscale)
    axes.set_yscale(yscale)
    axes.set_xlim(xlim)
    axes.set_ylim(ylim)
    if legend:
        axes.legend(legend)
    axes.grid()
    
#@save
def plot(X, Y=None, xlabel=None, ylabel=None, legend=None, xlim=None,
         ylim=None, xscale='linear', yscale='linear',
         fmts=('-', 'm--', 'g-.', 'r:'), figsize=(3.5, 2.5), axes=None):
    """绘制数据点。"""
    if legend is None:
        legend = []

    set_figsize(figsize)
    axes = axes if axes else d2l.plt.gca()

    # 如果 `X` 有一个轴，输出True
    def has_one_axis(X):
        return (hasattr(X, "ndim") and X.ndim == 1 or isinstance(X, list)
                and not hasattr(X[0], "__len__"))

    if has_one_axis(X):
        X = [X]
    if Y is None:
        X, Y = [[]] * len(X), X
    elif has_one_axis(Y):
        Y = [Y]
    if len(X) != len(Y):
        X = X * len(Y)
    axes.cla()
    for x, y, fmt in zip(X, Y, fmts):
        if len(x):
            axes.plot(x, y, fmt)
        else:
            axes.plot(y, fmt)
    set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend)
    
x = np.arange(0, 3, 0.1)
plot(x, [f(x), 2 * x - 3], 'x', 'f(x)', legend=['f(x)', 'Tangent line (x=1)'])

AttributeError: module 'torch' has no attribute 'plt'

## 2.5 自动求导


In [1]:
import torch

x = torch.arange(4.0,requires_grad=True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [2]:
x.requires_grad_(True)
x.grad

In [3]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [7]:
a = torch.randn(size=(), requires_grad=True)
a

tensor(-0.1502, requires_grad=True)

In [8]:
d = f(a)
d

tensor(-123006.9688, grad_fn=<MulBackward0>)

In [9]:
d.backward()

In [12]:
a.grad == d/a

tensor(True)

In [22]:
a = torch.randn(size=(),requires_grad=True)
a

tensor(0.2473, requires_grad=True)

In [33]:
a=a*2
a.sum()

tensor(7.9147, grad_fn=<SumBackward0>)

In [35]:
help(torch.distributions.Bernoulli)

Help on class Bernoulli in module torch.distributions.bernoulli:

class Bernoulli(torch.distributions.exp_family.ExponentialFamily)
 |  Bernoulli(probs=None, logits=None, validate_args=None)
 |  
 |  Creates a Bernoulli distribution parameterized by :attr:`probs`
 |  or :attr:`logits` (but not both).
 |  
 |  Samples are binary (0 or 1). They take the value `1` with probability `p`
 |  and `0` with probability `1 - p`.
 |  
 |  Example::
 |  
 |      >>> m = Bernoulli(torch.tensor([0.3]))
 |      >>> m.sample()  # 30% chance 1; 70% chance 0
 |      tensor([ 0.])
 |  
 |  Args:
 |      probs (Number, Tensor): the probability of sampling `1`
 |      logits (Number, Tensor): the log-odds of sampling `1`
 |  
 |  Method resolution order:
 |      Bernoulli
 |      torch.distributions.exp_family.ExponentialFamily
 |      torch.distributions.distribution.Distribution
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, probs=None, logits=None, validate_args=None)
 | 