## Preliminaries

```python
1. torch.arange: generate increasing sequence, return "tensor"

2. tensor.shape: shape
3. tensor.numel:
3. tensor.reshape(others,row,col)
```

In [16]:
import torch
x=torch.arange(12)
print(x)
print(x.shape)
print(x.numel())
X=x.reshape(3,4)
print(X)
print(X.shape)
print(X.numel)
print(torch.zeros((2,3,4)))
print(torch.ones(2,2))
print(torch.rand(2,2))
print(torch.randn(2,2))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
<built-in method numel of Tensor object at 0x7f6ffe0a7e00>
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.7624, 0.7603],
        [0.7381, 0.9149]])
tensor([[ 0.5657, -0.8454],
        [ 1.0570, -1.2559]])


In [18]:
# 运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y, x*y


(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]),
 tensor([ 2.,  4.,  8., 16.]))

In [19]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [20]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [21]:
print(X.shape)
print(Y.shape)

torch.Size([3, 4])
torch.Size([3, 4])


In [28]:
# cat的意思可以理解为加和某一个轴的元素
print(torch.cat((X,Y),dim=0).shape)
print(torch.cat((X,Y),dim=1).shape)

torch.Size([6, 4])
torch.Size([3, 8])


## broadcasting


In [29]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [31]:
c=a+b
c

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [39]:
# 切片在这里也可用
c[0,-1],c[:,-1]

(tensor(1), tensor([1, 2, 3]))

In [48]:
# .item转换成python标量
c[0,0].item()

0

## 2.2 数据预处理
pandas

In [49]:
import os
os.mkdir("./data/")

In [50]:
with open("./data/house_tiny.csv","w") as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [51]:
import pandas as pd

In [52]:
data=pd.read_csv("./data/house_tiny.csv")
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [53]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [54]:

inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [55]:
# pandas转tensor
import torch
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

## 2.3 线性代数

In [56]:
# 标量
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [57]:
# 向量，标里的列表
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [ ]:
# 长度=维度，多维叫形状
len(x),x.shape()