## Preliminaries

```python
1. torch.arange: generate increasing sequence, return "tensor"

2. tensor.shape: shape
3. tensor.numel:
3. tensor.reshape(others,row,col)
```

In [16]:
import torch
x=torch.arange(12)
print(x)
print(x.shape)
print(x.numel())
X=x.reshape(3,4)
print(X)
print(X.shape)
print(X.numel)
print(torch.zeros((2,3,4)))
print(torch.ones(2,2))
print(torch.rand(2,2))
print(torch.randn(2,2))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
<built-in method numel of Tensor object at 0x7f6ffe0a7e00>
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.7624, 0.7603],
        [0.7381, 0.9149]])
tensor([[ 0.5657, -0.8454],
        [ 1.0570, -1.2559]])
